"""
Copyright (c) 2026 Gabriel Guerrer

Distributed under the MIT license - See LICENSE for details
"""

"""
Test for the RAVA TCP server.

Launches a TCP server process and multiple client threads that simultaneously request random data
using different methods (byte streams, bytes, integers, and floats).
"""

import subprocess
import sys
import threading
import time

import rng_rava as rava


HOST = '127.0.0.1'
PORT = 4884
running = True

N_CLI_PER_TYPE = 3
N_GEN = 100
T_RUN = 5.
T_GEN_INTERVAL = 0.5
T_CLI_CONN_INTERVAL = 0.1

thread_errors = []


def run_client(target):
    try:
        target()

    except Exception as e:
        thread_errors.append(e)
        raise


def client_byte_stream():
    global running

    # Connect to the RAVA TCP server
    rng = rava.RAVA8_TCP()
    rng.open(HOST, PORT)

    # Starts byte stream and loops reading generated bytes
    rng.start_byte_stream(n_bytes=N_GEN, interval_ms=int(T_GEN_INTERVAL*1000))

    while running:
        rng.get_byte_stream()

    # Stop streaming and close the connection
    rng.stop_byte_stream()
    rng.close()


def client_bytes():
    global running

    # Connect to the RAVA TCP server
    rng = rava.RAVA8_TCP()
    rng.open(HOST, PORT)

    # Loops generating random bytes
    while running:
        rng.gen_bytes(n_bytes=N_GEN)
        time.sleep(T_GEN_INTERVAL)

    # Close the connection
    rng.close()


def client_ints():
    global running

    # Connect to the RAVA TCP server
    rng = rava.RAVA8_TCP()
    rng.open(HOST, PORT)

    # Loops generating random ints
    while running:
        rng.gen_int8s(n_ints=N_GEN, delta=100)
        time.sleep(T_GEN_INTERVAL)

    # Close the connection
    rng.close()


def client_floats():
    global running

    # Connect to the RAVA TCP server
    rng = rava.RAVA8_TCP()
    rng.open(HOST, PORT)

    # Loops generating random floats
    while running:
        rng.gen_floats(n_floats=N_GEN)
        time.sleep(T_GEN_INTERVAL)

    # Close the connection
    rng.close()


def test_rava_tcp():
    global running

    running = True
    thread_errors.clear()

    try:

        # Launch the TCP server using the same Python interpreter as the current process, inheriting the
        # Python environment
        p = subprocess.Popen(
            [sys.executable, '-m', 'rng_rava.tcp_srv', '--host', str(HOST), '--port', str(PORT)],
            stdout = subprocess.PIPE,
            stderr = subprocess.PIPE,
            text = True,
            )

        # Allow the server time to initialize
        time.sleep(0.5)

        assert p.poll() is None, 'TCP server failed to start'

        # Create client worker threads
        ths = []

        ## byte stream
        ths.append(threading.Thread(target=run_client, args=(client_byte_stream,)))

        ## bytes
        for _ in range(N_CLI_PER_TYPE):
            ths.append(threading.Thread(target=run_client, args=(client_bytes,)))

        ## ints
        for _ in range(N_CLI_PER_TYPE):
            ths.append(threading.Thread(target=run_client, args=(client_ints,)))

        ## floats
        for _ in range(N_CLI_PER_TYPE):
            ths.append(threading.Thread(target=run_client, args=(client_floats,)))

        # Start clients
        for th in ths:
            th.start()
            time.sleep(T_CLI_CONN_INTERVAL)

        # Run for T_RUN seconds
        t0 = time.time()
        while time.time() - t0 < T_RUN:
            assert p.poll() is None, 'TCP server exited unexpectedly'
            time.sleep(0.1)

        # Signal all clients to stop and wait for threads to exit
        running = False

        for th in ths:
            th.join()

        # Errors?
        assert not thread_errors, (
            'Exceptions occurred in client threads:\n'
            + '\n'.join(repr(e) for e in thread_errors)
        )

    finally:
        # Terminate the TCP server process
        p.terminate()

        try:
            stdout, stderr = p.communicate(timeout=5)

        except subprocess.TimeoutExpired:
            p.kill()
            stdout, stderr = p.communicate()

        assert p.returncode in (0, -15), (f'Unexpected server exit code: {p.returncode}')