"""
Copyright (c) 2026 Gabriel Guerrer

Distributed under the MIT license - See LICENSE for details
"""

"""
Randomness generation functionality.

The recommended configuration parameters for the RAVA RNG are as follows:
- PWM boost frequency: 50 kHz
- PWM boost duty-cycle setting: 20

These PWM boost parameters were determined experimentally by maximizing the avalanche pulse count 
while minimizing current consumption.

The recommended sampling interval is 10 µs. Values between 5 µs and 10 µs can increase the random 
number generation throughput at the cost of increased output bias. Sampling intervals below 5 µs 
may compromise the entropy of the generated data and are therefore not recommended.

Reference
Guerrer, G. (2023). Rava: An open hardware true random number generator based on avalanche noise. 
IEEE Access, 11, 119568-119583.
"""

from array import array
import enum
import queue
import struct

from .rava_comm import R_MessageComm, R_MessageError, QUEUE_READ_TIMEOUT_S
from .rava_errors import RAVAParameterError, RAVAFirmwareModuleError, \
    RAVAQueueTimeoutError, RAVAMissingQueueError, RAVAByteStreamingError
from .rava_pwm_boost import R_PwmBoostFreq, DEFAULT_PWM_BOOST_FREQ, DEFAULT_PWM_BOOST_DUTY

############################
# RAVA RNG
############################


DEFAULT_RNG_SAMPLING_INTERVAL_US = 10


class R_RngCores(enum.IntEnum):
    """
    RNG output modes based on the entropy cores A and B.

    AB_DUAL : Returns two separate output streams for cores A and B
    AB_ALT  : Returns a single stream with alternating bytes from A and B
    AB_XOR  : Returns a single stream formed by XORing corresponding bytes from A and B
    A       : Returns a single stream generated by core A
    B       : Returns a single stream generated by core A
    """

    AB_DUAL       = 0
    AB_ALT        = 1
    AB_XOR        = 2
    A             = 3
    B             = 4


DEFAULT_RNG_CORES = R_RngCores.AB_DUAL


class R_RngPP(enum.IntEnum):
    """
    Available byte post-processing modes.

    NONE       : No post-processing. Raw RNG bytes are returned unchanged
    XOR        : Generates two consecutive bytes and returns their bitwise XOR
    XOR DICHTL : Generates two consecutive bytes and combines them using the Dichtl method

    The XOR-based modes are provided for completeness and compatibility with traditional RNG
    post-processing approaches. They are not required for normal operation, as the RAVA
    architecture produces unbiased output bytes even when no post-processing is applied.

    Reference:
    M. Dichtl, "Bad and Good Ways of Post-processing Biased Physical Random Numbers",
    Fast Software Encryption (FSE 2007), Springer, 2007.
    """

    NONE          = 0
    XOR           = 1
    XOR_DICHTL    = 2


DEFAULT_RNG_POST_PROCESSING = R_RngPP.NONE


class RAVARngBytesStream:
    """
    Runtime state for fixed-interval random-byte streaming.
    """

    def __init__(self):
        self.streaming = False
        self.request_id = 0


class RAVARng():
    """
    Randomness generation commands.
    """

    def __init__(self):
        super().__init__()
        self.name = 'RAVARng'

        self.rng_bytes_stream_cfg = RAVARngBytesStream()


    def get_config(self):
        """
        Retrieve the current RNG configuration.
        """
        command_id = R_MessageComm.RNG_GET_CONFIG

        # IO Structure
        data_out_format = ''
        data_in_format = '<BBB'    # pwm_boost_freq_id, pwm_boost_duty, rng_sampling_interval

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, None)

        # Deserialize Input
        pwm_boost_freq_id, pwm_boost_duty, rng_sampling_interval = \
            struct.unpack(data_in_format, rmsg.data)

        # Process Input
        pwm_boost_freq = R_PwmBoostFreq(pwm_boost_freq_id)

        # Return Data
        return pwm_boost_freq, pwm_boost_duty, rng_sampling_interval


    def set_config(self, pwm_boost_freq = DEFAULT_PWM_BOOST_FREQ,
                         pwm_boost_duty = DEFAULT_PWM_BOOST_DUTY,
                         rng_sampling_interval = DEFAULT_RNG_SAMPLING_INTERVAL_US):
        """
        Update the RNG configuration using the provided parameters.        
        """
        command_id = R_MessageComm.RNG_SET_CONFIG

        # IO Structure
        data_out_format = '<BBB'
        data_in_format = ''

        # Validate Output
        if not(
            pwm_boost_freq < len(R_PwmBoostFreq) and
            pwm_boost_duty > 0 and
            rng_sampling_interval > 0
            ):

            raise RAVAParameterError(
                f'{self.name} {command_id.name} -> {R_MessageError.INVALID_INPUT_VALUES.name}'
                )

        # Serialize Output
        data_out = struct.pack(
            data_out_format, pwm_boost_freq, pwm_boost_duty, rng_sampling_interval)

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, data_out)

        # Return Data
        return True


    def set_timing_debug(self, on):
        """
        Enable/disable byte-generation timing debugging, exposed as a digital signal on a
        designated device output pin.

        This functionality needs to be enabled in the device firmware.
        """
        command_id = R_MessageComm.RNG_SET_TIMING_DEBUG

        # Enabled?
        if not self.firmw_modules.rng_timing_debug_enabled:

            raise RAVAFirmwareModuleError(
                f'{self.name} {command_id.name} -> RNG timing debug is disabled in the device firmware'
                )

        # IO Structure
        data_out_format = '<B'
        data_in_format = ''

        # Validate Output
        # Serialize Output
        data_out = struct.pack(data_out_format, on)

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, data_out)

        return True


    def gen_pulse_counts(self, n_counts, rng_cores=DEFAULT_RNG_CORES):
        """
        Retrieve pulse-count measurements.

        Parameters
        ----------
        n_counts : uint16
            Number of pulse-count samples to acquire from each selected RNG core.
            The maximum allowed value is `self.rng_gen_max_nbytes_per_core`.
        rng_cores : R_RngCores
            Specifies which RNG core(s) to use.

        Returns
        ----------
        pulse_counts : (array, array) or array
            Pulse-count samples from the selected RNG core(s).
        """
        command_id = R_MessageComm.RNG_GEN_PULSE_COUNTS

        # IO Structure
        data_out_format = '<HB'
        data_in_format = '<HB'
        array_res_type = 'B'

        # Validate Output
        if not(
            n_counts > 0 and
            n_counts <= self.rng_gen_max_nbytes_per_core and
            rng_cores < len(R_RngCores) and
            rng_cores != R_RngCores.AB_XOR
            ):

            raise RAVAParameterError(
                f'{self.name} {command_id.name} -> {R_MessageError.INVALID_INPUT_VALUES.name}'
                )

        # Serialize Output
        data_out = struct.pack(data_out_format, n_counts, rng_cores)

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, data_out)

        # Deserialize Input
        # n_counts_in, rng_cores_in = struct.unpack(data_in_format, rmsg.data)

        # Process Input
        if rng_cores == R_RngCores.AB_DUAL:
            pcs_a = array(array_res_type, rmsg.rand[::2])
            pcs_b = array(array_res_type, rmsg.rand[1::2])
            res = (pcs_a, pcs_b)

        else:
            pcs = array(array_res_type, rmsg.rand)
            res = pcs

        # Return Data
        return res


    def gen_bit(self, rng_cores=DEFAULT_RNG_CORES):
        """
        Retrieve random bits.

        Parameters
        ----------
        rng_cores : R_RngCores
            Specifies which RNG core(s) to use.

        Returns
        ----------
        bit : (bool, bool) or bool
            Bit samples from the selected RNG core(s).
        """
        command_id = R_MessageComm.RNG_GEN_BIT

        # IO Structure
        data_out_format = '<B'
        data_in_format = '<B'        

        # Validate Output
        if not(rng_cores < len(R_RngCores)):

            raise RAVAParameterError(
                f'{self.name} {command_id.name} -> {R_MessageError.INVALID_INPUT_VALUES.name}'
                )

        # Serialize Output
        data_out = struct.pack(data_out_format, rng_cores)

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, data_out)

        # Deserialize Input
        # rng_cores_in = struct.unpack(data_in_format, rmsg.data)

        # Process Input
        if rng_cores in [R_RngCores.AB_DUAL, R_RngCores.AB_ALT]:
            res = rmsg.rand[0], rmsg.rand[1]

        else:
            res = rmsg.rand[0]

        # Return Data
        return res


    def gen_bytes(self, n_bytes, rng_cores=DEFAULT_RNG_CORES, postproc=DEFAULT_RNG_POST_PROCESSING):
        """
        Retrieve random bytes.

        Parameters
        ----------
        n_bytes : uint16
            Number of random bytes to acquire from each selected RNG core.
            The maximum allowed value is `self.rng_gen_max_nbytes_per_core`.
        rng_cores : R_RngCores
            Specifies which RNG core(s) to use.
        postproc : R_RngPP
            Specifies the postprocessing mode.

        Returns
        ----------
        random_bytes : (array, array) or array
            Random bytes from the selected RNG core(s).
        """
        command_id = R_MessageComm.RNG_GEN_BYTES

        # IO Structure
        data_out_format = '<HBB'
        data_in_format = '<HBB'
        array_res_type = 'B'

        # Validate Output
        if not(
            n_bytes > 0 and
            n_bytes <= self.rng_gen_max_nbytes_per_core and
            rng_cores < len(R_RngCores) and
            postproc < len(R_RngPP)
            ):

            raise RAVAParameterError(
                f'{self.name} {command_id.name} -> {R_MessageError.INVALID_INPUT_VALUES.name}'
                )

        # Serialize Output
        data_out = struct.pack(data_out_format, n_bytes, rng_cores, postproc)

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, data_out)

        # Deserialize Input
        # n_bytes_in, rng_cores_in, postproc_in = struct.unpack(data_in_format, rmsg.data)

        # Process Input
        if rng_cores == R_RngCores.AB_DUAL:
            rnd_a = array(array_res_type, rmsg.rand[::2])
            rnd_b = array(array_res_type, rmsg.rand[1::2])
            res = rnd_a, rnd_b

        else:
            rnd = array(array_res_type, rmsg.rand)
            res = rnd

        # Return Data
        return res


    def gen_int8s(self, n_ints, delta, postproc=DEFAULT_RNG_POST_PROCESSING):
        """
        Retrieve 8-bit integers uniformly distributed over the interval [0, delta].

        Parameters
        ----------
        n_ints : uint16
            Number of ints to acquire.
            The maximum allowed value is `2 * self.rng_gen_max_nbytes_per_core`.
        delta : uint8
            Specifies the outcome interval as [0, int_delta].
        postproc : R_RngPP
            Specifies the postprocessing mode.

        Returns
        ----------
        ints : array
            Random ints generated.
        """
        command_id = R_MessageComm.RNG_GEN_INT8S

        # IO Structure
        data_out_format = '<HBB'
        data_in_format = '<HBB'
        array_res_type = 'B'

        # Validate Output
        if not(
            n_ints > 0 and
            n_ints <= 2 * self.rng_gen_max_nbytes_per_core and
            delta > 0 and
            postproc < len(R_RngPP)
            ):

            raise RAVAParameterError(
                f'{self.name} {command_id.name} -> {R_MessageError.INVALID_INPUT_VALUES.name}'
                )

        # Serialize Output
        data_out = struct.pack(data_out_format, n_ints, delta, postproc)

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, data_out)

        # Deserialize Input
        # n_ints_in, delta_in, postproc_in = struct.unpack(data_in_format, rmsg.data)

        # Process Input
        ints = array(array_res_type, rmsg.rand)

        # Return Data
        return ints


    def gen_int16s(self, n_ints, delta, postproc=DEFAULT_RNG_POST_PROCESSING):
        """
        Retrieve 16-bit integers uniformly distributed over the interval [0, delta].

        Parameters
        ----------
        n_ints : uint16
            Number of ints to acquire.
            The maximum allowed value is `self.rng_gen_max_nbytes_per_core`.
        delta : uint16
            Specifies the outcome interval as [0, int_delta].
        postproc : R_RngPP
            Specifies the postprocessing mode.

        Returns
        ----------
        ints : array
            Random ints generated.
        """
        command_id = R_MessageComm.RNG_GEN_INT16S

        # IO Structure
        data_out_format = '<HHB'
        data_in_format = '<HHB'
        array_res_type = 'H'

        # Validate Output
        if not(
            n_ints > 0 and
            n_ints <= self.rng_gen_max_nbytes_per_core and
            delta > 0 and
            postproc < len(R_RngPP)
            ):

            raise RAVAParameterError(
                f'{self.name} {command_id.name} -> {R_MessageError.INVALID_INPUT_VALUES.name}'
                )

        # Serialize Output
        data_out = struct.pack(data_out_format, n_ints, delta, postproc)

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, data_out)

        # Deserialize Input
        # n_ints_in, delta_in, postproc_in = struct.unpack(data_in_format, rmsg.data)

        # Process Input
        ints = array(array_res_type, rmsg.rand)

        # Return Data
        return ints


    def gen_floats(self, n_floats, postproc=DEFAULT_RNG_POST_PROCESSING):
        """
        Retrieve floats uniformly distributed over the interval [0, 1).

        Parameters
        ----------
        n_floats : uint16
            Number of floats to acquire.
            The maximum allowed value is `self.rng_gen_max_nbytes_per_core / 2`.
        postproc : R_RngPP
            Specifies the postprocessing mode.

        Returns
        ----------
        floats : array
            Random floats generated.
        """
        command_id = R_MessageComm.RNG_GEN_FLOATS

        # IO Structure
        data_out_format = '<HB'
        data_in_format = '<HB'
        array_res_type = 'f'

        # Validate Output
        if not(
            n_floats > 0 and
            n_floats <= self.rng_gen_max_nbytes_per_core / 2 and
            postproc < len(R_RngPP)
            ):

            raise RAVAParameterError(
                f'{self.name} {command_id.name} -> {R_MessageError.INVALID_INPUT_VALUES.name}'
                )

        # Serialize Output
        data_out = struct.pack(data_out_format, n_floats, postproc)

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, data_out)

        # Deserialize Input
        # n_floats_in, postproc_in = struct.unpack(data_in_format, rmsg.data)

        # Process Input
        floats = array(array_res_type, rmsg.rand)

        # Return Data
        return floats


    def gen_floats_downey(self, n_floats, postproc=DEFAULT_RNG_POST_PROCESSING):
        """
        Retrieve floats uniformly distributed over the interval [0, 1) using the method described
        in: Downey, Allen B. "Generating pseudo-random floating-point values"
        https://www.allendowney.com/research/rand/downey07randfloat.pdf

        Parameters
        ----------
        n_floats : uint16
            Number of floats to acquire.
            The maximum allowed value is `self.rng_gen_max_nbytes_per_core / 2`.
        postproc : R_RngPP
            Specifies the postprocessing mode.

        Returns
        ----------
        floats : array
            Random floats generated.
        """
        command_id = R_MessageComm.RNG_GEN_FLOATS_DOWNEY

        # IO Structure
        data_out_format = '<HB'
        data_in_format = '<HB'
        array_res_type = 'f'

        # Validate Output
        if not(
            n_floats > 0 and
            n_floats <= self.rng_gen_max_nbytes_per_core / 2 and
            postproc < len(R_RngPP)
            ):

            raise RAVAParameterError(
                f'{self.name} {command_id.name} -> {R_MessageError.INVALID_INPUT_VALUES.name}'
                )

        # Serialize Output
        data_out = struct.pack(data_out_format, n_floats, postproc)

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, data_out)

        # Deserialize Input
        # n_floats_in, postproc_in = struct.unpack(data_in_format, rmsg.data)

        # Process Input
        floats = array(array_res_type, rmsg.rand)

        # Return Data
        return floats


    def start_byte_stream(self, n_bytes, interval_ms,
                                rng_cores=DEFAULT_RNG_CORES, postproc=DEFAULT_RNG_POST_PROCESSING):
        """
        Request to start periodic random-byte streaming.

        Parameters
        ----------
        n_bytes : uint16
            Number of random bytes to acquire from each selected RNG core.
            The maximum allowed value is `self.rng_gen_max_nbytes_per_core`.
        interval_ms : uint16
            Time interval, in milliseconds, between successive byte-generation events.
        rng_cores : R_RngCores
            Specifies which RNG core(s) to use.
        postproc : R_RngPP
            Specifies the postprocessing mode.

        Returns
        ----------
        True
        """
        command_id = R_MessageComm.RNG_START_BYTE_STREAM

        # Is streaming?
        if self.rng_bytes_stream_cfg.streaming:
            raise RAVAByteStreamingError(f'{self.name} {command_id.name} -> Already streaming')

        # IO Structure
        data_out_format = '<HHBB'
        data_in_format = ''

        # Validate Output
        if not(
            n_bytes > 0 and
            n_bytes <= self.rng_gen_max_nbytes_per_core and
            rng_cores < len(R_RngCores) and
            postproc < len(R_RngPP)
            ):

            raise RAVAParameterError(
                f'{self.name} {command_id.name} -> {R_MessageError.INVALID_INPUT_VALUES.name}'
                )

        # Serialize Output
        data_out = struct.pack(data_out_format, n_bytes, interval_ms, rng_cores, postproc)

        # Send Request
        request_id, q = self.send_rava_msg(command_id, data_out)

        # Get msg from queue
        try:
            rmsg = q.get(timeout=QUEUE_READ_TIMEOUT_S)

        except queue.Empty as err:
            raise RAVAQueueTimeoutError(
                f'{self.name} send_retrieve_rava_msg -> Empty Queue'
                ) from err

        # Test for error
        rmsg.validate()

        # Deserialize Input
        # Process Input
        self.rng_bytes_stream_cfg.streaming = True
        self.rng_bytes_stream_cfg.request_id = request_id

        # Return Data
        return True


    def get_byte_stream(self):
        """
        Retrieve random bytes produced by the asynchronous byte-stream generator. Bytes are
        returned in FIFO order.

        Returns
        ----------
        random_bytes : (array, array) or array
            Random bytes from the selected RNG core(s).
        """
        command_id = R_MessageComm.RNG_GEN_BYTES_STREAM

        # Is streaming?
        if not self.rng_bytes_stream_cfg.streaming:

            raise RAVAByteStreamingError(f'{self.name} {command_id.name} -> Not streaming')

        # IO Structure
        data_out_format = ''
        data_in_format = '<HHBB'
        array_res_type = 'B'

        # Get queue
        q = self.comm_pending_msgs.get(self.rng_bytes_stream_cfg.request_id, None)

        if q is None:
            raise RAVAMissingQueueError(
                f'{self.name} {command_id.name} -> Pending message queue '
                f'not found for request_id {rmsg.req_id}'
                )

        # Get msg
        try:
            rmsg = q.get(timeout=QUEUE_READ_TIMEOUT_S)

        except queue.Empty as err:
            self.log.info(f'{self.name} {command_id.name} -> No message available')
            return None

        # Test for error
        rmsg.validate()

        # Deserialize Input
        n_bytes, interval_ms, rng_cores, postproc = struct.unpack(data_in_format, rmsg.data)

        if rng_cores == R_RngCores.AB_DUAL:
            rnd_a = array(array_res_type, rmsg.rand[::2])
            rnd_b = array(array_res_type, rmsg.rand[1::2])
            res = rnd_a, rnd_b

        else:
            rnd = array(array_res_type, rmsg.rand)
            res = rnd

        # Process Input
        # Return Data
        return res


    def get_status_byte_stream(self):
        """
        Request to inform whether fixed-interval random-byte generation is enabled and the
        associated request identifier.

        Returns
        ----------
        streaming : bool
            True if periodic random-byte streaming is enabled.
        req_id : uint8
            Request ID associated with the streaming process.
        """
        command_id = R_MessageComm.RNG_GET_STATUS_BYTE_STREAM

        # IO Structure
        data_out_format = ''
        data_in_format = '<?H' # streaming, req_id

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, None)

        # Deserialize Input
        streaming, req_id, = struct.unpack(data_in_format, rmsg.data)

        # Process Input
        # Return Data
        return streaming, req_id


    def stop_byte_stream(self):
        """
        Request to stop periodic random-byte streaming.
        """
        command_id = R_MessageComm.RNG_STOP_BYTE_STREAM

        # Is streaming?
        if not self.rng_bytes_stream_cfg.streaming:
            return True

        # IO Structure
        data_out_format = ''
        data_in_format = ''

        # Send and Retrieve Request
        rmsg = self.send_retrieve_rava_msg(command_id, None)

        # Deserialize Input
        # Process Input

        ## Remove stream queue from pending list
        self.comm_pending_msgs.pop(self.rng_bytes_stream_cfg.request_id)

        ## Update
        self.rng_bytes_stream_cfg.streaming = False
        self.rng_bytes_stream_cfg.request_id = 0

        # Return Data
        return True
