"""
Copyright (c) 2026 Gabriel Guerrer

Distributed under the MIT license - See LICENSE for details
"""

"""
Implements the host-side communication protocol used by RAVA devices.

The protocol establishes a leader/follower architecture in which the host initiates communication
by issuing requests, and the RAVA device responds accordingly. Most commands operate synchronously,
with the exception of the byte stream command, which enables asynchronous communication. Once
started by the host, the device periodically transmits data until the host issues a request to stop
the stream.

Communication is implemented using framed binary messages with the following layout:

[SOF1][SOF2][CLI_ID][REQ_ID][REQ_ERR][CMD_ID][R_LEN][D_LEN][...DATA][CRC16][...RAND]
   1     1      1       1       1        1      2      1     D_LEN     2     R_LEN

Where:
- SOF1, SOF2: Start-of-frame characters, defined respectively as '!' and '$'

- CLI_ID: Client identifier (256 possible values)
  - Enables an asynchronous request-response protocol for multiple clients sharing the same device

- REQ_ID: Request identifier (256 possible values)
  - Enables asynchronous request-response matching on the host side, allowing concurrent requests
    to be tracked independently

- REQ_ERR: Request error/status code
  - Defined in the `R_MessageError` enum

- CMD_ID: Command identifier
  - Command identifiers defined in `R_MessageComm`

- R_LEN: Number of random payload bytes
  - The maximum value is informed by the device via `dev_get_info()` and stored in the variable
    'rng_gen_max_nbytes_per_core'
  - Commands sent to the RAVA device must always use R_LEN == 0
  - Responses generated by the device use R_LEN > 0 when returning randomness data

- D_LEN: Length of the header data field
  - Maximum value defined in `COMM_DATA_MAX_LEN`

- DATA: Optional message parameters data (D_LEN bytes)
  - The firmware serializes and deserializes C types using little-endian byte order.
  - Host implementations must ensure: little-endian encoding, correct serialization/deserialization,
    and proper type sizes when reconstructing data structures

- CRC16: 16-bit CRC calculated over the message header
  - Calculated from REQ_ID through DATA, covering 7 + D_LEN bytes
  - Uses the CRC-16/CCITT (PPP/IrDA reflected variant) algorithm

- RAND: Optional random payload (R_LEN bytes)

- The total message length is: 11 + D_LEN + R_LEN bytes
"""

import enum
import struct

from .rava_errors import *
from .rava_tools import crc16_ccitt_update

############################
# RAVA COMM PROTOCOL
############################


FIRMWARE_MIN_VERSION_MAJOR = 3
FIRMWARE_MIN_VERSION_MINOR = 0
FIRMWARE_MIN_VERSION_PATCH = 0

COMM_SOF_1 = b'!'
COMM_SOF_2 = b'$'
COMM_SOF = b'!$'
COMM_HEADER_MIN_LEN = 11
COMM_DATA_MAX_LEN = 53

RNG_GEN_MAX_NBYTES_PER_CORE = 1024


class R_MessageComm(enum.IntEnum):
    """
    Command IDs exchanged between host and RAVA firmware.
    """

    DEVICE_PING                     = 0
    DEVICE_GET_INFO                 = 1
    DEVICE_GET_USAGE                = 2
    DEVICE_GET_FREE_RAM             = 3
    DEVICE_GET_TEMPERATURE          = 4
    DEVICE_GET_VCC                  = 5
    DEVICE_MONITOR                  = 6

    RNG_GET_CONFIG                  = 10
    RNG_SET_CONFIG                  = 11
    RNG_SET_TIMING_DEBUG            = 12
    RNG_GEN_PULSE_COUNTS            = 13
    RNG_GEN_BIT                     = 14
    RNG_GEN_BYTES                   = 15
    RNG_GEN_BYTES_STREAM            = 16

    RNG_GEN_INT8S                   = 17
    RNG_GEN_INT16S                  = 18
    RNG_GEN_FLOATS                  = 19
    RNG_GEN_FLOATS_DOWNEY           = 20

    RNG_START_BYTE_STREAM           = 25
    RNG_GET_STATUS_BYTE_STREAM      = 26
    RNG_STOP_BYTE_STREAM            = 27

    HEALTH_STARTUP_RUN              = 30
    HEALTH_STARTUP_GET_RESULTS      = 31
    HEALTH_CONTINUOUS_GET_ERRORS    = 32

    EEPROM_RESET_TO_DEFAULT         = 35
    EEPROM_RNG_GET_CONFIG           = 36
    EEPROM_RNG_SET_CONFIG           = 37

    PERIPH_DIGI                     = 45

    PERIPH_D1_DIGI_FAST             = 49
    PERIPH_D1_TRIGGER_INPUT         = 50
    PERIPH_D1_COMPARATOR            = 51
    PERIPH_D1_DELAY_US_TEST         = 52

    PERIPH_D2_TIMER3_INPUT_CAPTURE  = 55

    PERIPH_D3_TIMER3_TRIGGER_OUTPUT = 58
    PERIPH_D3_TIMER3_PWM            = 59
    PERIPH_D3_TIMER3_SOUND          = 60

    PERIPH_D4_PIN_CHANGE            = 64

    PERIPH_D5_ADC                   = 67


class R_MessageState(enum.IntEnum):
    """
    States used by the RAVA protocol parser.
    """

    WAIT_SOF_A              = 0
    WAIT_SOF_B              = 1
    READ_CLI_ID             = 2
    READ_REQ_ID             = 3
    READ_REQ_ERROR          = 4
    READ_CMD_ID             = 5
    READ_CMD_RAND_LEN_A     = 6
    READ_CMD_RAND_LEN_B     = 7
    READ_DATA_LEN           = 8
    READ_DATA               = 9
    READ_CRC_A              = 10
    READ_CRC_B              = 11
    READ_RAND               = 12


class R_MessageError(enum.IntEnum):
    """
    Error IDs returned by firmware.

    These values are transmitted inside protocol packets and converted into Python exceptions by
    send_retrieve_rava_msg().
    """

    OK                      = 0
    INVALID_COMM_ID         = 1
    INVALID_CRC             = 2
    INVALID_RAND_LEN        = 3
    INVALID_DATA_LEN        = 4
    INVALID_INPUT_TYPES     = 5
    INVALID_INPUT_VALUES    = 6
    HEALTH_STARTUP_FAILED   = 7
    BYTE_STREAM_BUSY        = 8
    TIMER_BUSY              = 9
    COMMAND_NOT_ALLOWED     = 10
    ERROR                   = 11


class RAVAMessageState:
    """
    Runtime state of the RAVA protocol parser.
    """

    def __init__(self):
        self.id = 0
        self.crc = 0
        self.crc_rcv = 0
        self.data_idx = 0


class RAVAMessageBuffer:
    """
    Receive buffer for RAVA protocol messages used by the protocol parser.
    """

    def __init__(self):
        self.client_id = 0
        self.request_id = 0
        self.request_error = 0
        self.command_id = 0
        self.data_len = 0
        self.data = bytearray(COMM_DATA_MAX_LEN)
        self.rand_len = 0


class RAVAMessage:
    """
    RAVA protocol message.
    """

    def __init__(self,
            client_id = 0, request_id = 0, request_error = 0, command_id = 0, data = b'', rand = b'',
            rmsg_buf: RAVAMessageBuffer | None = None
            ):
        """
        Initialize a protocol message.

        If `rmsg_buf` is provided, initialize the message from the parsed contents of the receive
        buffer. Otherwise, initialize it from the supplied field values.
        """
        self.name = 'RAVAMessage'

        if isinstance(rmsg_buf, RAVAMessageBuffer):
            self.client_id = rmsg_buf.client_id
            self.request_id = rmsg_buf.request_id
            self.request_error = rmsg_buf.request_error
            self.command_id = rmsg_buf.command_id
            self.data_len = rmsg_buf.data_len
            self.data = rmsg_buf.data[:rmsg_buf.data_len]
            self.rand_len = rmsg_buf.rand_len
            self.rand = b''

        else:
            data = data if data is not None else b''
            rand = rand if rand is not None else b''

            self.client_id = client_id
            self.request_id = request_id
            self.request_error = request_error
            self.command_id = command_id
            self.data_len = len(data)
            self.data = data
            self.rand_len = len(rand)
            self.rand = rand

        try:
            self.command_name = R_MessageComm(self.command_id).name
        except ValueError:
            self.command_name = self.command_id

        try:
            self.request_error_name = R_MessageError(self.request_error).name
        except ValueError:
            self.request_error_name = self.request_error


    def __repr__(self):
        """
        Return a string representation of the message.
        """

        rmsg_str = f'CLI_ID = {self.client_id}, REQ_ID = {self.request_id}, ' \
                   f'REQ_ERR = {self.request_error_name}, COMM = {self.command_name}, ' \
                   f'RAND_LEN = {self.rand_len}, DATA_LEN = {self.data_len}'

        return rmsg_str


    def validate(self):
        """
        Validate the message status.

        This method assumes the message has already been processed by the parser or other function
        that detects protocol and device errors. If an error has been identified, the corresponding
        exception is raised.
        """

        # Ok
        if self.request_error == R_MessageError.OK:
            return

        # Error
        error_txt = f'{self.name} validate : {self.command_name} -> {self.request_error_name}'

        # RAVAProtocolError
        if self.request_error in [
            R_MessageError.INVALID_RAND_LEN,
            R_MessageError.INVALID_DATA_LEN,
            R_MessageError.INVALID_CRC,
            R_MessageError.INVALID_COMM_ID
            ]:
            raise RAVAProtocolError(error_txt)

        # RAVAParameterError
        elif self.request_error in [
            R_MessageError.INVALID_INPUT_TYPES,
            R_MessageError.INVALID_INPUT_VALUES
            ]:
            raise RAVAParameterError(error_txt)

        # RAVAByteStreamingError
        elif self.request_error == R_MessageError.BYTE_STREAM_BUSY:
            raise RAVAByteStreamingError(error_txt)

        # RAVAHealthError
        elif self.request_error == R_MessageError.HEALTH_STARTUP_FAILED:
            raise RAVAHealthError(error_txt)

        # RAVADeviceError
        else:
            raise RAVADeviceError(error_txt)


    def to_bytes(self):
        """
        Serialize the message into the RAVA binary protocol format.

        To include a random payload, assign it to `self.rand` before calling this method.
        """

        # Transform to a bytes object
        data = self.data if self.data is not None else b''
        rand = self.rand if self.rand is not None else b''

        data_bytes_len = len(data)
        rand_bytes_len = len(rand)

        rmsg_len = COMM_HEADER_MIN_LEN + data_bytes_len + rand_bytes_len
        rmsg_bytes = bytearray(rmsg_len)

        # Pack header fields
        struct.pack_into(
            f'<BBBBBBHB{data_bytes_len}s',
            rmsg_bytes,
            0,
            ord(COMM_SOF_1),
            ord(COMM_SOF_2),
            self.client_id,
            self.request_id,
            int(self.request_error),
            int(self.command_id),
            rand_bytes_len,
            data_bytes_len,
            data
            )

        # Compute CRC
        crc_data_start = COMM_HEADER_MIN_LEN - 2 + data_bytes_len

        crc = 0xFFFF
        for b in memoryview(rmsg_bytes)[2:crc_data_start]:
            crc = crc16_ccitt_update(crc, b)

        # Complete protocol message
        struct.pack_into(
            f'<H{rand_bytes_len}s',
            rmsg_bytes,
            crc_data_start,
            crc,
            rand
        )

        return rmsg_bytes


class RAVAMessageParser:
    """
    Incremental parser for the RAVA binary protocol.
    """

    def __init__(self, rng_gen_max_nbytes_per_core = RNG_GEN_MAX_NBYTES_PER_CORE):
        self.rng_gen_max_nbytes_per_core = rng_gen_max_nbytes_per_core

        self.msg_state = RAVAMessageState()
        self.msg_buffer = RAVAMessageBuffer()


    def update_gen_max_nbytes(self, rng_gen_max_nbytes_per_core):
        """
        Update the maximum number of random bytes that may be requested in a protocol message.
        """

        self.rng_gen_max_nbytes_per_core = rng_gen_max_nbytes_per_core


    def random_payload_retrieved(self):
        """
        Reset the parser after the random payload has been read, preparing the parser to receive
        the next protocol message.
        """

        self.msg_state.id = R_MessageState.WAIT_SOF_A


    def parse_byte(self, byte):
        """
        Feed one byte into the RAVA protocol parser.

        This method implements a finite-state machine that reconstructs a RAVA protocol message
        from an incoming byte stream. Once a complete protocol header has been received, a snapshot
        of the parsed message is returned.

        The header spans from the start-of-frame (SOF) marker through the CRC field. If the message
        contains a random payload (`rand_len > 0`), the payload bytes are not included in the
        returned snapshot and must be read separately to obtain the complete protocol message.
        The caller is responsible for reading the indicated number of random bytes before invoking
        `random_payload_retrieved()`.

        Messages reporting protocol or device errors are also considered complete and are returned
        immediately so they can be handled by the caller.

        Parameters
        ----------
        byte : byte
            A single byte from the incoming data stream.

        Returns
        ----------
        RAVAMessage
            If a complete message header has been assembled; otherwise None.
        """

        if isinstance(byte, (bytes, bytearray)):
            byte = byte[0]

        CS = R_MessageState
        CE = R_MessageError
        state = self.msg_state
        rmsg = self.msg_buffer

        # SOF
        if state.id == CS.WAIT_SOF_A:
            rmsg.request_error = CE.OK
            if byte == COMM_SOF_1[0]:
                state.id = CS.WAIT_SOF_B

        elif state.id == CS.WAIT_SOF_B:
            if byte == COMM_SOF_2[0]:
                state.id = CS.READ_CLI_ID
            elif byte == COMM_SOF_1[0]:
                state.id = CS.WAIT_SOF_B
            else:
                state.id = CS.WAIT_SOF_A

        # CLI_ID
        elif state.id == CS.READ_CLI_ID:
            rmsg.client_id = byte
            state.crc = crc16_ccitt_update(0xFFFF, byte)
            state.id = CS.READ_REQ_ID

        # REQ_ID
        elif state.id == CS.READ_REQ_ID:
            rmsg.request_id = byte
            state.crc = crc16_ccitt_update(state.crc, byte)
            state.id = CS.READ_REQ_ERROR

        # READ_REQ_ERROR
        elif state.id == CS.READ_REQ_ERROR:
            rmsg.request_error = byte
            state.crc = crc16_ccitt_update(state.crc, byte)
            state.id = CS.READ_CMD_ID

        # CMD_ID
        elif state.id == CS.READ_CMD_ID:
            rmsg.command_id = byte
            state.crc = crc16_ccitt_update(state.crc, byte)
            state.id = CS.READ_CMD_RAND_LEN_A

        # RAND_LEN
        elif state.id == CS.READ_CMD_RAND_LEN_A:
            rmsg.rand_len = byte
            state.crc = crc16_ccitt_update(state.crc, byte)
            state.id = CS.READ_CMD_RAND_LEN_B

        elif state.id == CS.READ_CMD_RAND_LEN_B:
            rmsg.rand_len |= (byte << 8)
            state.crc = crc16_ccitt_update(state.crc, byte)

            # Error
            if rmsg.rand_len > 2 * self.rng_gen_max_nbytes_per_core:
                rmsg.request_error = CE.INVALID_RAND_LEN
                state.id = CS.WAIT_SOF_A
                return RAVAMessage(rmsg_buf=rmsg)

            state.id = CS.READ_DATA_LEN

        # DATA_LEN
        elif state.id == CS.READ_DATA_LEN:
            rmsg.data_len = byte
            state.crc = crc16_ccitt_update(state.crc, byte)
            state.data_idx = 0

            # Error
            if rmsg.data_len > COMM_DATA_MAX_LEN:
                rmsg.request_error = CE.INVALID_DATA_LEN
                state.id = CS.WAIT_SOF_A
                return RAVAMessage(rmsg_buf=rmsg)

            if rmsg.data_len == 0:
                state.id = CS.READ_CRC_A
            else:
                state.id = CS.READ_DATA

        # DATA
        elif state.id == CS.READ_DATA:
            rmsg.data[state.data_idx] = byte
            state.data_idx += 1
            state.crc = crc16_ccitt_update(state.crc, byte)

            if state.data_idx >= rmsg.data_len:
                state.id = CS.READ_CRC_A

        # CRC
        elif state.id == CS.READ_CRC_A:
            state.crc_rcv = byte
            state.id = CS.READ_CRC_B

        elif state.id == CS.READ_CRC_B:
            state.crc_rcv |= (byte << 8)

            # Error
            if state.crc_rcv != state.crc:
                rmsg.request_error = CE.INVALID_CRC
                state.id = CS.WAIT_SOF_A
                return RAVAMessage(rmsg_buf=rmsg)

            # Command found
            if rmsg.rand_len == 0:
                state.id = CS.WAIT_SOF_A
            else:
                state.id = CS.READ_RAND

            return RAVAMessage(rmsg_buf=rmsg)

        return None