 
"""
Copyright (c) 2026 Gabriel Guerrer

Distributed under the MIT license - See LICENSE for details
"""

"""
Stress test for the RAVA TCP server.

The test launches a TCP server process and a large number of client threads that simultaneously 
request random data using different generation methods (byte streams, bytes, integers, and floats). 
It is designed to exercise the server under heavy load.
"""

import subprocess
import sys
import threading
import time

import rng_rava as rava

HOST = '127.0.0.1'
PORT = 4884
running = True

N_CLI_PER_TYPE = 50
N_GEN = 100
T_RUN = 60.
T_CLI_CONN_INTERVAL = 0.1


def client_byte_stream():
    global running

    # Connect to the RAVA TCP server
    rng = rava.RAVA8_TCP()
    rng.open(HOST, PORT)

    # Starts byte stream and loops reading generated bytes
    # The short streaming interval causes the byte stream to dominate the device's random number 
    # generation
    rng.start_byte_stream(n_bytes=N_GEN, interval_ms=10)

    while running:
        rng.get_byte_stream()

    # Stop streaming and close the connection
    rng.stop_byte_stream()
    rng.close()


def client_bytes():
    global running

    # Connect to the RAVA TCP server
    rng = rava.RAVA8_TCP()
    rng.open(HOST, PORT)

    # Loops generating random bytes
    while running:
        rng.gen_bytes(n_bytes=N_GEN)
        # No delay between requests. This maximizes the request rate and verifies that the server 
        # correctly enforces a single outstanding request per client

    # Close the connection
    rng.close()


def client_ints():
    global running

    # Connect to the RAVA TCP server
    rng = rava.RAVA8_TCP()
    rng.open(HOST, PORT)

    # Loops generating random ints
    while running:
        rng.gen_int8s(n_ints=N_GEN, delta=100)
        # No delay between requests. This maximizes the request rate and verifies that the server 
        # correctly enforces a single outstanding request per client

    # Close the connection
    rng.close()


def client_floats():
    global running

    # Connect to the RAVA TCP server
    rng = rava.RAVA8_TCP()
    rng.open(HOST, PORT)

    # Loops generating random floats
    while running:
        rng.gen_floats(n_floats=N_GEN)
        # No delay between requests. This maximizes the request rate and verifies that the server 
        # correctly enforces a single outstanding request per client

    # Close the connection
    rng.close()


# Start the TCP server using the same Python interpreter as the current process, inheriting the
# Python environment
p = subprocess.Popen(
    [sys.executable, '-m', 'rng_rava.tcp_srv', '--host', str(HOST), '--port', str(PORT)]     
    )

# Allow the server time to initialize
time.sleep(0.5)

assert p.poll() is None, "TCP server failed to start"

# Create client worker threads
ths = []

## byte stream
ths.append(threading.Thread(target=client_byte_stream))

## bytes
for _ in range(N_CLI_PER_TYPE):
    ths.append(threading.Thread(target=client_bytes))

## ints
for _ in range(N_CLI_PER_TYPE):
    ths.append(threading.Thread(target=client_ints))

## floats
for _ in range(N_CLI_PER_TYPE):
    ths.append(threading.Thread(target=client_floats))

# Start clients
for th in ths:
    th.start()
    time.sleep(T_CLI_CONN_INTERVAL)

# Run for T_RUN seconds
time.sleep(T_RUN)

# Signal all clients to stop and wait for threads to exit
running = False

for th in ths:
    th.join()

# Terminate the TCP server process
p.terminate()
p.wait()