# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

<<<<<<< HEAD
name: Upload Python Package
=======
name: Publish to PyPI
>>>>>>> 4fcf521 (Update v3.0.0)

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
<<<<<<< HEAD
  deploy:

    runs-on: ubuntu-latest
    
    environment:
      name: pypi
      url: https://pypi.org/p/rng_rava
    permissions:
=======
  publish:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/rng_rava

    permissions:
      contents: read
>>>>>>> 4fcf521 (Update v3.0.0)
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4
<<<<<<< HEAD
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1     
=======

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Build release distributions
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
        python -m build

    - name: Verify package
      run: twine check dist/*

    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
          packages-dir: dist/
>>>>>>> 4fcf521 (Update v3.0.0)
